<?php
/**
 * In-house integration allow-list for the front-end isolation mu-plugin.
 *
 * The isolation mu-plugin (generated by {@see Installer::mu_plugin_content()})
 * strips every non-allow-listed plugin on BuddyNext front-end routes to save
 * memory. That mu-plugin runs on `option_active_plugins`, BEFORE any regular
 * plugin has loaded — so a partner integration cannot register a runtime filter
 * in time to keep itself alive. Historically the allow-list was hard-coded in
 * the mu-plugin, which meant it drifted out of sync (a "half-cooked" mu-plugin)
 * and silently stripped integrations whose VERSION constants then never defined
 * on the front end — killing their Portfolio panels and nav.
 *
 * The fix: BuddyNext owns the canonical in-house integration family here and
 * persists it to the `buddynext_isolation_plugins` option. The mu-plugin reads
 * that option directly (raw SQL, same early-bootstrap pattern as the route
 * slugs) and merges it into the allow-list — so the mu-plugin is data-driven and
 * can never go stale. The list is declared unconditionally (NOT gated on whether
 * a partner is installed or active): listing an absent plugin is harmless because
 * the mu-plugin intersects the allow-list with the genuinely-active set, but it
 * guarantees that the moment a partner is activated it is already allowed through
 * — "always wire in-house integrations, installed or not".
 *
 * Extension seam: `buddynext_isolation_plugins` (string[]) — BuddyNext Pro adds
 * its application-layer integrations (Career Board, Listora, Learnomy) here.
 *
 * @package BuddyNext\Core
 */

declare( strict_types=1 );

namespace BuddyNext\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Maintains the canonical in-house integration allow-list for the mu-plugin.
 */
class PluginIsolation {

	/**
	 * Option that mirrors the canonical integration allow-list to the mu-plugin.
	 *
	 * Stored as a JSON string so the mu-plugin — which reads the raw option_value
	 * before the WordPress option API is available — can decode it with the native
	 * json_decode() without depending on PHP unserialisation semantics.
	 */
	public const OPTION = 'buddynext_isolation_plugins';

	/**
	 * In-house integration plugin basenames that the front end must never strip.
	 *
	 * BuddyNext + BuddyNext Pro themselves are the mu-plugin's safety floor and
	 * stay hard-coded there; this list is the integration FAMILY around them. It
	 * is intentionally unconditional — every in-house partner, free or pro, listed
	 * whether or not it is currently installed/active.
	 */
	private const CORE_INTEGRATIONS = array(
		// Core integrations (BuddyNext Free first-class).
		'wpmediaverse/wpmediaverse.php',
		'wpmediaverse-pro/wpmediaverse-pro.php',
		'jetonomy/jetonomy.php',
		'jetonomy-pro/jetonomy-pro.php',
		'wb-gamification/wb-gamification.php',
	);

	/**
	 * Wire the runtime option-sync pass.
	 *
	 * @return void
	 */
	public function init(): void {
		// Late on init: Pro's wire_extensions() (plugins_loaded) has already added
		// its `buddynext_isolation_plugins` filter, so the persisted option carries
		// the full free+pro family. The guarded write below is a no-op unless the
		// list actually changed, so this is cheap on every request.
		add_action( 'init', array( $this, 'sync_option' ), 20 );
	}

	/**
	 * The canonical in-house integration allow-list (free + filtered Pro additions).
	 *
	 * @return array<int,string> De-duplicated plugin basenames.
	 */
	public static function integration_plugins(): array {
		/**
		 * Filter the in-house integration plugins kept alive on BuddyNext routes.
		 *
		 * BuddyNext Pro appends its application-layer integrations here. Entries are
		 * plugin basenames (`dir/file.php`); listing one that is not installed is
		 * harmless.
		 *
		 * @param array<int,string> $plugins In-house integration basenames.
		 */
		$plugins = (array) apply_filters( 'buddynext_isolation_plugins', self::CORE_INTEGRATIONS );

		$plugins = array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( $p ): string => is_string( $p ) ? trim( $p ) : '',
						$plugins
					)
				)
			)
		);

		sort( $plugins ); // Deterministic order so the guarded write only fires on real changes.

		return $plugins;
	}

	/**
	 * Persist the canonical allow-list to the mirror option when it has changed.
	 *
	 * Idempotent: reads the stored JSON, compares against the freshly-collected
	 * list, and only writes on a genuine diff — so it adds no write on a steady
	 * state but self-heals the moment Pro is (de)activated or the family changes.
	 *
	 * @return void
	 */
	public function sync_option(): void {
		$desired = self::integration_plugins();
		$stored  = json_decode( (string) get_option( self::OPTION, '' ), true );

		if ( is_array( $stored ) && $stored === $desired ) {
			return;
		}

		update_option( self::OPTION, (string) wp_json_encode( $desired ), false );
	}
}
