<?php
/**
 * In-house integration allow-list for the front-end isolation mu-plugin.
 *
 * The isolation mu-plugin (generated by {@see Installer::mu_plugin_content()})
 * strips every non-allow-listed plugin on BuddyNext front-end routes to save
 * memory. That mu-plugin runs on `option_active_plugins`, BEFORE any regular
 * plugin has loaded — so a partner integration cannot register a runtime filter
 * in time to keep itself alive. Historically the allow-list was hard-coded in
 * the mu-plugin, which meant it drifted out of sync (a "half-cooked" mu-plugin)
 * and silently stripped integrations whose VERSION constants then never defined
 * on the front end — killing their Portfolio panels and nav.
 *
 * The fix: BuddyNext owns the canonical in-house integration family here and
 * persists it to the `buddynext_isolation_plugins` option. The mu-plugin reads
 * that option directly (raw SQL, same early-bootstrap pattern as the route
 * slugs) and merges it into the allow-list — so the mu-plugin is data-driven and
 * can never go stale. The list is declared unconditionally (NOT gated on whether
 * a partner is installed or active): listing an absent plugin is harmless because
 * the mu-plugin intersects the allow-list with the genuinely-active set, but it
 * guarantees that the moment a partner is activated it is already allowed through
 * — "always wire in-house integrations, installed or not".
 *
 * Extension seam: `buddynext_isolation_plugins` (string[]) — BuddyNext Pro adds
 * its application-layer integrations (Career Board, Listora, Learnomy) here.
 *
 * @package BuddyNext\Core
 */

declare( strict_types=1 );

namespace BuddyNext\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Maintains the canonical in-house integration allow-list for the mu-plugin.
 */
class PluginIsolation {

	/**
	 * Option that mirrors the canonical integration allow-list to the mu-plugin.
	 *
	 * Stored as a JSON string so the mu-plugin — which reads the raw option_value
	 * before the WordPress option API is available — can decode it with the native
	 * json_decode() without depending on PHP unserialisation semantics.
	 */
	public const OPTION = 'buddynext_isolation_plugins';

	/**
	 * Cache of the auto-detected front-end plugin set.
	 *
	 * Holds `fingerprint` (of the active-plugin list) and `plugins`, so the
	 * reflection scan reruns when the owner activates or deactivates something and
	 * not on every admin page load.
	 */
	public const DETECTED_OPTION = 'buddynext_isolation_detected';

	/**
	 * In-house integration plugin basenames that the front end must never strip.
	 *
	 * BuddyNext + BuddyNext Pro themselves are the mu-plugin's safety floor and
	 * stay hard-coded there; this list is the integration FAMILY around them. It
	 * is intentionally unconditional — every in-house partner, free or pro, listed
	 * whether or not it is currently installed/active.
	 */
	private const CORE_INTEGRATIONS = array(
		// Core integrations (BuddyNext Free first-class).
		'wpmediaverse/wpmediaverse.php',
		'wpmediaverse-pro/wpmediaverse-pro.php',
		'jetonomy/jetonomy.php',
		'jetonomy-pro/jetonomy-pro.php',
		'wb-gamification/wb-gamification.php',
		// WB Member Blog. MemberBlogBridge's Articles profile tab guards on
		// BUDDYPRESS_MEMBER_BLOG_VERSION, and /members/ is a BuddyNext front-end
		// route — so leaving it off this list strips the plugin exactly where the
		// tab is rendered and the tab silently disappears. That is the failure this
		// class was written to stop, one integration later.
		'buddypress-member-blog/buddypress-member-blog.php',
		// Pro's entry file is class-prefixed, unlike every other pair here. Taken
		// from `wp plugin list --field=file`, not guessed from the directory name.
		'buddypress-member-blog-pro/class-buddypress-member-blog-pro.php',
	);

	/**
	 * Pro application-layer integrations that contribute Portfolio panels/tabs.
	 *
	 * Separate from CORE_INTEGRATIONS only so the two groups stay readable; both
	 * are part of the same floor and neither may be stripped.
	 */
	private const APP_INTEGRATIONS = array(
		'wp-career-board/wp-career-board.php',
		'wp-career-board-pro/wp-career-board-pro.php',
		'wb-listora/wb-listora.php',
		'wb-listora-pro/wb-listora-pro.php',
		'learnomy/learnomy.php',
		'learnomy-pro/learnomy-pro.php',
		'eventonomy/eventonomy.php',
		'eventonomy-pro/eventonomy-pro.php',
	);

	/**
	 * Operational plugins that must survive isolation.
	 *
	 * Stripping the object cache drop-in's admin plugin or the profiler does not
	 * remove a member-visible feature, but it makes the hub routes behave
	 * differently from the rest of the site, which is exactly what makes a
	 * performance problem impossible to diagnose.
	 */
	private const OPERATIONAL_PLUGINS = array(
		'redis-cache/redis-cache.php',
		'query-monitor/query-monitor.php',
	);

	/**
	 * BuddyNext itself. The mu-plugin's own safety floor.
	 */
	private const SELF_PLUGINS = array(
		'buddynext/buddynext.php',
		'buddynext-pro/buddynext-pro.php',
	);

	/**
	 * The mu-plugin's keep-alive FLOOR. One definition, rendered into the file.
	 *
	 * Deliberately wider than what sync_option() merges at runtime, and the
	 * difference is not an oversight:
	 *
	 *  - sync_option() merges CORE_INTEGRATIONS + TRANSLATION_PLUGINS + the owner's
	 *    list, and Pro appends its application-layer family through the
	 *    `buddynext_isolation_plugins` filter. That is the correct split - Free
	 *    does not decide Pro's integrations.
	 *  - the mu-plugin cannot wait for any of that. It runs before plugins load,
	 *    so no filter has fired and the option may be empty or stale. Its floor
	 *    therefore hardcodes the whole in-house family, Pro's included, so
	 *    Portfolio tabs and nav survive the very first request.
	 *
	 * What WAS wrong is that this floor existed twice: once here in constants and
	 * once as a hand-written array inside the mu-plugin source in Installer, held
	 * together by a comment reading "keep in sync". A comment is not a sync
	 * mechanism. Installer now renders this list into the generated file, so the
	 * copy on disk is derived rather than maintained.
	 *
	 * The generated mu-plugin still contains a literal array, because it must - it
	 * cannot call into this class. Nobody has to type it twice.
	 *
	 * @return array<int,string> Plugin basenames, de-duplicated.
	 */
	public static function essentials(): array {
		return array_values(
			array_unique(
				array_merge(
					self::SELF_PLUGINS,
					self::CORE_INTEGRATIONS,
					self::APP_INTEGRATIONS,
					self::OPERATIONAL_PLUGINS,
					self::TRANSLATION_PLUGINS
				)
			)
		);
	}

	/**
	 * Owner-managed option: extra plugin basenames to keep alive on BN routes.
	 *
	 * Separate from self::OPTION because that one is REWRITTEN from the canonical
	 * family on every sync — an owner's choices stored there would be erased the
	 * next time Pro was toggled. This is the owner's list; sync_option() merges it
	 * into the mirror the mu-plugin reads, so no mu-plugin change is required and
	 * an older on-disk copy keeps working.
	 */
	public const OPTION_KEEP = 'buddynext_isolation_keep';

	/**
	 * String-override plugins that isolation must never strip.
	 *
	 * These do not add a feature — they rewrite EVERY string on the page through
	 * `gettext` / `load_textdomain_mofile`. Stripping one does not disable
	 * something the visitor can see is missing; it silently serves BuddyNext's own
	 * English while the owner's translation sits on disk being ignored, and only on
	 * the hub routes, which is precisely where the terminology matters most
	 * (renaming "Spaces" to "Teams"). A translation plugin is also cheap — Loco's
	 * front-end footprint is a single filter — so this costs nothing measurable
	 * against the memory isolation is there to save.
	 *
	 * Anything not listed here is covered by the owner-facing allow-list screen
	 * (Admin -> BuddyNext -> Plugin isolation), so this is a sensible default, not
	 * the only way in.
	 */
	private const TRANSLATION_PLUGINS = array(
		'loco-translate/loco.php',
		'polylang/polylang.php',
		'polylang-pro/polylang.php',
		'sitepress-multilingual-cms/sitepress.php',
		'wpml-string-translation/plugin.php',
		'translatepress-multilingual/index.php',
		'say-what/say-what.php',
	);

	/**
	 * The owner's extra keep-alive basenames, sanitised.
	 *
	 * @return array<int,string>
	 */
	public static function owner_keep_list(): array {
		$stored = get_option( self::OPTION_KEEP, array() );

		if ( ! is_array( $stored ) ) {
			return array();
		}

		return array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( $p ): string => is_string( $p ) ? trim( $p ) : '',
						$stored
					)
				)
			)
		);
	}

	/**
	 * Wire the runtime option-sync pass.
	 *
	 * @return void
	 */
	public function init(): void {
		// Attach the type-owner collectors before anything registers a taxonomy or
		// post type (those land on `init`). Self-gates to the admin and to a changed
		// plugin set, so on the steady state this call does nothing at all.
		$this->maybe_collect_type_owners();

		// Late on init: Pro's wire_extensions() (plugins_loaded) has already added
		// its `buddynext_isolation_plugins` filter, so the persisted option carries
		// the full free+pro family. The guarded write below is a no-op unless the
		// list actually changed, so this is cheap on every request.
		add_action( 'init', array( $this, 'sync_option' ), 20 );

		// Bust the menu object-type cache whenever a nav menu changes, so isolation
		// never reasons over a stale set (menu edits are rare; this is cheap).
		add_action( 'wp_update_nav_menu', array( __CLASS__, 'flush_menu_types_cache' ) );
		add_action( 'wp_update_nav_menu_item', array( __CLASS__, 'flush_menu_types_cache' ) );
		add_action( 'wp_delete_nav_menu', array( __CLASS__, 'flush_menu_types_cache' ) );
	}

	/**
	 * The canonical in-house integration allow-list (free + filtered Pro additions).
	 *
	 * @return array<int,string> De-duplicated plugin basenames.
	 */
	public static function integration_plugins(): array {
		/**
		 * Filter the in-house integration plugins kept alive on BuddyNext routes.
		 *
		 * BuddyNext Pro appends its application-layer integrations here. Entries are
		 * plugin basenames (`dir/file.php`); listing one that is not installed is
		 * harmless.
		 *
		 * @param array<int,string> $plugins In-house integration basenames.
		 */
		$base = array_merge(
			self::CORE_INTEGRATIONS,
			self::TRANSLATION_PLUGINS,
			self::owner_keep_list(),
			self::menu_dependency_plugins(),
			self::detected_frontend_plugins()
		);

		$plugins = (array) apply_filters( 'buddynext_isolation_plugins', $base );

		$plugins = array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( $p ): string => is_string( $p ) ? trim( $p ) : '',
						$plugins
					)
				)
			)
		);

		sort( $plugins ); // Deterministic order so the guarded write only fires on real changes.

		return $plugins;
	}

	/**
	 * Option holding the object-type -> plugin-basename map, plus the signature of
	 * the plugin set it was built from.
	 *
	 * @var string
	 */
	public const OPTION_OWNERS = 'buddynext_isolation_type_owners';

	/**
	 * Object cache group + key for the menu object-type set (see menu_object_types()).
	 *
	 * The set is derived from `_menu_item_object` postmeta and only changes when a
	 * nav menu is edited, so it is cached and busted on menu writes (init() wires the
	 * hooks) rather than left to a blind TTL. The group follows the shared
	 * `buddynext_<domain>` convention enforced by bin/check-cache.sh.
	 */
	private const CACHE_GROUP = 'buddynext_isolation';

	/**
	 * Cache key for the menu object-type set.
	 *
	 * @var string
	 */
	private const CACHE_KEY_MENU_TYPES = 'menu_object_types';

	/**
	 * Plugins that must stay loaded because the site's NAV MENUS depend on them.
	 *
	 * This is the fix for a live customer defect. Isolation strips non-allow-listed
	 * plugins on BuddyNext routes; when a stripped plugin owns a taxonomy or post
	 * type, that type is never registered, and WordPress then treats every nav menu
	 * item pointing at it as invalid and DROPS IT (`wp_setup_nav_menu_item()` sets
	 * `_invalid`, `wp_get_nav_menu_items()` filters those out on the front end).
	 * The owner sees menu links present on every normal page and silently missing on
	 * /activity/, /spaces/, /login/ - reported as WooCommerce `product_cat` links
	 * vanishing from a footer menu, with Elementor and a consent banner going the
	 * same way.
	 *
	 * Restoring the item without the plugin is not an option: `_menu_item_url` is
	 * EMPTY for taxonomy and post-type items (verified on a real menu row) because
	 * the URL is resolved at runtime by `get_term_link()`, which needs the taxonomy
	 * registered. Un-invalidating the item would render a link to nowhere, which is
	 * worse than dropping it. The plugin genuinely has to stay loaded.
	 *
	 * Deliberately GENERIC rather than a hardcoded list of popular plugins. A
	 * hardcoded list is endless and always one plugin behind the site that breaks.
	 * This keeps whatever the owner's menus actually reference, whatever registered
	 * it.
	 *
	 * Safe by construction: it can only ADD to the allow-list, so the worst case is
	 * that isolation keeps more plugins alive than strictly necessary - a smaller
	 * saving, never a broken page.
	 *
	 * @return array<int,string> Plugin basenames.
	 */
	public static function menu_dependency_plugins(): array {
		$types = self::menu_object_types();
		if ( array() === $types ) {
			return array();
		}

		$owners = get_option( self::OPTION_OWNERS, array() );
		$map    = is_array( $owners ) && isset( $owners['map'] ) && is_array( $owners['map'] ) ? $owners['map'] : array();
		if ( array() === $map ) {
			return array();
		}

		$keep = array();
		foreach ( $types as $type ) {
			if ( isset( $map[ $type ] ) && is_string( $map[ $type ] ) && '' !== $map[ $type ] ) {
				$keep[] = $map[ $type ];
			}
		}

		return array_values( array_unique( $keep ) );
	}

	/**
	 * Object types (taxonomies / post types) referenced by any nav menu item.
	 *
	 * One indexed postmeta read. Menu items store their target in
	 * `_menu_item_object` ('product_cat', 'page', ...); custom-URL items store
	 * nothing here and are unaffected by isolation, so they never appear.
	 *
	 * @return array<int,string>
	 */
	private static function menu_object_types(): array {
		global $wpdb;

		$types = wp_cache_get( self::CACHE_KEY_MENU_TYPES, self::CACHE_GROUP );
		if ( is_array( $types ) ) {
			return $types;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- result is cached on the line below; no core API returns "every object type referenced by any menu" without loading every menu item.
		$rows = $wpdb->get_col(
			"SELECT DISTINCT meta_value FROM {$wpdb->postmeta} WHERE meta_key = '_menu_item_object' AND meta_value <> ''"
		);

		$types = array_values( array_unique( array_map( 'strval', (array) $rows ) ) );
		// TTL is a backstop only; the real freshness guarantee is the menu-write bust
		// wired in init() -> flush_menu_types_cache().
		wp_cache_set( self::CACHE_KEY_MENU_TYPES, $types, self::CACHE_GROUP, HOUR_IN_SECONDS );

		return $types;
	}

	/**
	 * Bust the cached menu object-type set.
	 *
	 * Wired to the nav-menu write hooks in init(). The set is a projection of
	 * `_menu_item_object` postmeta, so the only thing that can change it is a menu
	 * edit — busting here keeps isolation reasoning over a current object-type set
	 * instead of one up to an hour stale (a menu item pointing at a freshly
	 * registered CPT would otherwise be mis-classified until the TTL lapsed).
	 *
	 * @return void
	 */
	public static function flush_menu_types_cache(): void {
		wp_cache_delete( self::CACHE_KEY_MENU_TYPES, self::CACHE_GROUP );
	}

	/**
	 * Record which plugin registered which taxonomy / post type.
	 *
	 * Nothing in WordPress records the registering plugin, so it is captured at
	 * registration time from the call stack. That is not free, so it runs ONLY when
	 * the active-plugin set has changed since the map was built, and only in the
	 * admin - never on a front-end request.
	 *
	 * Hooked from init() at `plugins_loaded`, because registrations happen on
	 * `init` and the collectors must already be attached.
	 *
	 * @return void
	 */
	public function maybe_collect_type_owners(): void {
		if ( ! is_admin() ) {
			return;
		}

		$signature = md5( (string) wp_json_encode( (array) get_option( 'active_plugins', array() ) ) );
		$stored    = get_option( self::OPTION_OWNERS, array() );
		if ( is_array( $stored ) && ( $stored['signature'] ?? '' ) === $signature ) {
			return;
		}

		$map = array();

		$collect = static function ( string $type ) use ( &$map ): void {
			if ( isset( $map[ $type ] ) ) {
				return;
			}
			$basename = self::registering_plugin();
			if ( '' !== $basename ) {
				$map[ $type ] = $basename;
			}
		};

		add_action( 'registered_taxonomy', $collect, 10, 1 );
		add_action( 'registered_post_type', $collect, 10, 1 );

		// Persist after every registration has run. Priority 19 so the map is stored
		// before sync_option() reads it at 20.
		add_action(
			'init',
			static function () use ( &$map, $signature ): void {
				update_option(
					self::OPTION_OWNERS,
					array(
						'signature' => $signature,
						'map'       => $map,
					),
					false
				);
			},
			19
		);
	}

	/**
	 * Resolve the plugin basename that registered the type being processed.
	 *
	 * Returns '' for anything registered by core, a theme or a mu-plugin - none of
	 * which isolation strips, so none of which needs keeping.
	 *
	 * @return string Plugin basename, or '' when not resolvable.
	 */
	private static function registering_plugin(): string {
		if ( ! defined( 'WP_PLUGIN_DIR' ) ) {
			return '';
		}

		// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_debug_backtrace -- the only way to attribute a registration to its plugin; runs once per plugin-set change, admin-only.
		$frames = debug_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS );

		// Use the frame for register_taxonomy() / register_post_type() itself: in a
		// PHP backtrace that frame's `file` is the file which CALLED it, i.e. the
		// plugin doing the registering.
		//
		// Do NOT simply take the first frame inside any plugin directory. The stack
		// here runs back through our own collector, so the first plugin frame is
		// always BuddyNext - which is what the first cut of this did, cheerfully
		// attributing core's `post` and `page` to buddynext/buddynext.php.
		$file = '';
		foreach ( $frames as $frame ) {
			$fn = (string) $frame['function'];
			if ( 'register_taxonomy' === $fn || 'register_post_type' === $fn ) {
				$file = isset( $frame['file'] ) ? wp_normalize_path( (string) $frame['file'] ) : '';
				break;
			}
		}

		$plugin_dir = wp_normalize_path( WP_PLUGIN_DIR ) . '/';
		if ( '' === $file || ! str_starts_with( $file, $plugin_dir ) ) {
			return '';
		}

		$parts = explode( '/', substr( $file, strlen( $plugin_dir ) ) );
		$dir   = $parts[0] ?? '';
		if ( '' === $dir ) {
			return '';
		}

		// Single-file plugin: the basename IS the file.
		if ( 1 === count( $parts ) ) {
			return $dir;
		}

		// Directory plugin: active_plugins stores `dir/main-file.php`, and the main
		// file rarely matches the directory name, so resolve it from the active list
		// rather than guessing.
		foreach ( (array) get_option( 'active_plugins', array() ) as $active ) {
			if ( is_string( $active ) && str_starts_with( $active, $dir . '/' ) ) {
				return $active;
			}
		}

		return '';
	}

	/**
	 * Persist the canonical allow-list to the mirror option when it has changed.
	 *
	 * Idempotent: reads the stored JSON, compares against the freshly-collected
	 * list, and only writes on a genuine diff — so it adds no write on a steady
	 * state but self-heals the moment Pro is (de)activated or the family changes.
	 *
	 * @return void
	 */
	/**
	 * Hooks that mean "this plugin puts something on the front end".
	 *
	 * Deliberately about OUTPUT rather than intent. A plugin that only listens to
	 * save_post or registers a REST route changes nothing a visitor sees on a
	 * BuddyNext route, and isolation is exactly right to drop it. A plugin that
	 * hooks wp_head, enqueues assets, filters the_content, or contributes to the
	 * header/footer template is drawing part of the page, and dropping it makes
	 * the community pages look broken compared with the rest of the site.
	 *
	 * @var string[]
	 */
	private const FRONTEND_OUTPUT_HOOKS = array(
		'wp_head',
		'wp_footer',
		'wp_body_open',
		'wp_enqueue_scripts',
		'get_header',
		'get_footer',
		'the_content',
		'body_class',
		'template_include',
		'wp_nav_menu_items',
		'render_block',
		'language_attributes',
	);

	/**
	 * Active plugins that render on the front end, detected rather than listed.
	 *
	 * WHY THIS EXISTS. Isolation strips every plugin that is not on an allow-list,
	 * and an allow-list of THIRD-PARTY plugins can never be complete: we cannot
	 * know what an owner installed. The reported symptom was a Gutenberg
	 * header/footer builder vanishing on hub routes, but that plugin was only the
	 * one somebody noticed -- cookie banners, page builders, sliders, custom-CSS
	 * plugins and analytics were all being dropped the same way, silently, and the
	 * owner's only clue was that their community pages looked different from the
	 * rest of their site (Basecamp 10180566662).
	 *
	 * So the list is now discovered. Every active plugin is asked one question --
	 * does it hook anything that draws the front end? -- and if it does, it
	 * survives isolation. An owner installing a new front-end plugin is protected
	 * without anyone editing a list.
	 *
	 * WHY IT ONLY RUNS IN ADMIN. Detection has to happen on a request where every
	 * plugin is loaded. On an isolated front-end route the stripped plugins are not
	 * loaded, so they register no hooks, so they would look like they render
	 * nothing -- and isolation would permanently confirm its own decision. The
	 * mu-plugin is a no-op in wp-admin, which makes admin the one context that
	 * always sees the full set.
	 *
	 * The result is cached against the active-plugin set, so the reflection cost is
	 * paid once per change rather than on every admin page load.
	 *
	 * @return string[] Plugin basenames.
	 */
	private static function detected_frontend_plugins(): array {
		$cached = get_option( self::DETECTED_OPTION, array() );
		$known  = ( is_array( $cached ) && is_array( $cached['plugins'] ?? null ) ) ? $cached['plugins'] : array();

		/*
		 * Only scan on a request where every plugin is actually loaded.
		 *
		 * On an ISOLATED route the stripped plugins register no hooks, so they would
		 * look like they render nothing and isolation would keep confirming its own
		 * decision forever. The mu-plugin exposes buddynext_mu_is_bn_request(), so we
		 * can ask it directly rather than guessing.
		 */
		$isolated = function_exists( 'buddynext_mu_is_bn_request' ) && buddynext_mu_is_bn_request();
		if ( $isolated ) {
			return $known;
		}

		$active      = (array) get_option( 'active_plugins', array() );
		$fingerprint = md5( (string) wp_json_encode( $active ) );

		// The owner changed which plugins are active: start again rather than
		// carrying findings about a plugin they have since turned off.
		if ( ! is_array( $cached ) || ( $cached['fingerprint'] ?? '' ) !== $fingerprint ) {
			$known = array();
		}

		/*
		 * ACCUMULATE across contexts instead of replacing.
		 *
		 * A plugin may register its front-end hooks only on front-end requests --
		 * Yoast is the obvious one -- so an admin-only scan reports it as rendering
		 * nothing and isolation strips it from the very hub pages whose titles and
		 * meta it is supposed to own. An admin scan and a front-end scan each see a
		 * partial picture; the union is the true one, and the fingerprint above is
		 * what stops it growing stale.
		 */
		$detected = array_values( array_unique( array_merge( $known, self::scan_frontend_hooks() ) ) );
		sort( $detected );

		if ( $detected === $known && is_array( $cached ) && ( $cached['fingerprint'] ?? '' ) === $fingerprint ) {
			return $known;
		}

		update_option(
			self::DETECTED_OPTION,
			array(
				'fingerprint' => $fingerprint,
				'plugins'     => $detected,
			),
			false
		);

		return $detected;
	}

	/**
	 * Walk the output hooks and map each callback back to the plugin that added it.
	 *
	 * Reflection is the only way to ask "which file registered this callback?" --
	 * WordPress records no provenance for a hook. It is not cheap, which is why
	 * {@see self::detected_frontend_plugins()} caches the answer.
	 *
	 * @return string[] Sorted plugin basenames.
	 */
	private static function scan_frontend_hooks(): array {
		global $wp_filter;

		$found      = array();
		$plugin_dir = wp_normalize_path( WP_PLUGIN_DIR );

		foreach ( self::FRONTEND_OUTPUT_HOOKS as $hook ) {
			if ( empty( $wp_filter[ $hook ] ) || ! $wp_filter[ $hook ] instanceof \WP_Hook ) {
				continue;
			}

			foreach ( $wp_filter[ $hook ]->callbacks as $callbacks ) {
				foreach ( $callbacks as $registered ) {
					$file = self::callback_file( $registered['function'] ?? null );
					if ( '' === $file ) {
						continue;
					}

					$file = wp_normalize_path( $file );
					if ( 0 !== strpos( $file, $plugin_dir . '/' ) ) {
						// A theme, a must-use plugin or core. None of those are
						// stripped by isolation, so none of them need allowing.
						continue;
					}

					$relative = ltrim( substr( $file, strlen( $plugin_dir ) ), '/' );
					$slug     = strtok( $relative, '/' );
					if ( ! is_string( $slug ) ) {
						continue;
					}

					$found[ $slug ] = true;
				}
			}
		}

		// A slug is not a basename. Resolve each against the genuinely active set
		// so the allow-list carries the same "dir/file.php" the mu-plugin compares.
		$plugins = array();
		foreach ( (array) get_option( 'active_plugins', array() ) as $basename ) {
			$basename = (string) $basename;
			$slug     = strtok( $basename, '/' );
			if ( is_string( $slug ) && isset( $found[ $slug ] ) ) {
				$plugins[] = $basename;
			}
		}

		sort( $plugins );

		return $plugins;
	}

	/**
	 * The file a hook callback was defined in, or an empty string.
	 *
	 * @param mixed $callback Anything WordPress accepts as a callable.
	 * @return string Absolute path, or '' when it cannot be resolved.
	 */
	private static function callback_file( $callback ): string {
		try {
			if ( is_string( $callback ) && function_exists( $callback ) ) {
				$ref = new \ReflectionFunction( $callback );
			} elseif ( $callback instanceof \Closure ) {
				$ref = new \ReflectionFunction( $callback );
			} elseif ( is_array( $callback ) && 2 === count( $callback ) && ( is_object( $callback[0] ) || is_string( $callback[0] ) ) ) {
				$ref = new \ReflectionMethod( $callback[0], (string) $callback[1] );
			} elseif ( is_object( $callback ) && method_exists( $callback, '__invoke' ) ) {
				$ref = new \ReflectionMethod( $callback, '__invoke' );
			} else {
				return '';
			}
		} catch ( \Throwable $e ) {
			// A callback we cannot reflect is one we cannot attribute. Skipping it
			// only means its plugin is not auto-detected from THIS hook; the owner
			// keep-list remains the manual override.
			return '';
		}

		return (string) $ref->getFileName();
	}

	/**
	 * Mirror the canonical allow-list into the option the mu-plugin reads.
	 *
	 * Guarded: the option is only written when the computed list actually differs,
	 * so an unchanged site does not write on every request.
	 *
	 * @return void
	 */
	public function sync_option(): void {
		$desired = self::integration_plugins();
		$stored  = json_decode( (string) get_option( self::OPTION, '' ), true );

		if ( is_array( $stored ) && $stored === $desired ) {
			return;
		}

		update_option( self::OPTION, (string) wp_json_encode( $desired ), false );
	}
}
