<?php
/**
 * In-house integration allow-list for the front-end isolation mu-plugin.
 *
 * The isolation mu-plugin (generated by {@see Installer::mu_plugin_content()})
 * strips every non-allow-listed plugin on BuddyNext front-end routes to save
 * memory. That mu-plugin runs on `option_active_plugins`, BEFORE any regular
 * plugin has loaded — so a partner integration cannot register a runtime filter
 * in time to keep itself alive. Historically the allow-list was hard-coded in
 * the mu-plugin, which meant it drifted out of sync (a "half-cooked" mu-plugin)
 * and silently stripped integrations whose VERSION constants then never defined
 * on the front end — killing their Portfolio panels and nav.
 *
 * The fix: BuddyNext owns the canonical in-house integration family here and
 * persists it to the `buddynext_isolation_plugins` option. The mu-plugin reads
 * that option directly (raw SQL, same early-bootstrap pattern as the route
 * slugs) and merges it into the allow-list — so the mu-plugin is data-driven and
 * can never go stale. The list is declared unconditionally (NOT gated on whether
 * a partner is installed or active): listing an absent plugin is harmless because
 * the mu-plugin intersects the allow-list with the genuinely-active set, but it
 * guarantees that the moment a partner is activated it is already allowed through
 * — "always wire in-house integrations, installed or not".
 *
 * Extension seam: `buddynext_isolation_plugins` (string[]) — BuddyNext Pro adds
 * its application-layer integrations (Career Board, Listora, Learnomy) here.
 *
 * @package BuddyNext\Core
 */

declare( strict_types=1 );

namespace BuddyNext\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Maintains the canonical in-house integration allow-list for the mu-plugin.
 */
class PluginIsolation {

	/**
	 * Option that mirrors the canonical integration allow-list to the mu-plugin.
	 *
	 * Stored as a JSON string so the mu-plugin — which reads the raw option_value
	 * before the WordPress option API is available — can decode it with the native
	 * json_decode() without depending on PHP unserialisation semantics.
	 */
	public const OPTION = 'buddynext_isolation_plugins';

	/**
	 * In-house integration plugin basenames that the front end must never strip.
	 *
	 * BuddyNext + BuddyNext Pro themselves are the mu-plugin's safety floor and
	 * stay hard-coded there; this list is the integration FAMILY around them. It
	 * is intentionally unconditional — every in-house partner, free or pro, listed
	 * whether or not it is currently installed/active.
	 */
	private const CORE_INTEGRATIONS = array(
		// Core integrations (BuddyNext Free first-class).
		'wpmediaverse/wpmediaverse.php',
		'wpmediaverse-pro/wpmediaverse-pro.php',
		'jetonomy/jetonomy.php',
		'jetonomy-pro/jetonomy-pro.php',
		'wb-gamification/wb-gamification.php',
		// WB Member Blog. MemberBlogBridge's Articles profile tab guards on
		// BUDDYPRESS_MEMBER_BLOG_VERSION, and /members/ is a BuddyNext front-end
		// route — so leaving it off this list strips the plugin exactly where the
		// tab is rendered and the tab silently disappears. That is the failure this
		// class was written to stop, one integration later.
		'buddypress-member-blog/buddypress-member-blog.php',
		// Pro's entry file is class-prefixed, unlike every other pair here. Taken
		// from `wp plugin list --field=file`, not guessed from the directory name.
		'buddypress-member-blog-pro/class-buddypress-member-blog-pro.php',
	);

	/**
	 * Pro application-layer integrations that contribute Portfolio panels/tabs.
	 *
	 * Separate from CORE_INTEGRATIONS only so the two groups stay readable; both
	 * are part of the same floor and neither may be stripped.
	 */
	private const APP_INTEGRATIONS = array(
		'wp-career-board/wp-career-board.php',
		'wp-career-board-pro/wp-career-board-pro.php',
		'wb-listora/wb-listora.php',
		'wb-listora-pro/wb-listora-pro.php',
		'learnomy/learnomy.php',
		'learnomy-pro/learnomy-pro.php',
		'eventonomy/eventonomy.php',
		'eventonomy-pro/eventonomy-pro.php',
	);

	/**
	 * Operational plugins that must survive isolation.
	 *
	 * Stripping the object cache drop-in's admin plugin or the profiler does not
	 * remove a member-visible feature, but it makes the hub routes behave
	 * differently from the rest of the site, which is exactly what makes a
	 * performance problem impossible to diagnose.
	 */
	private const OPERATIONAL_PLUGINS = array(
		'redis-cache/redis-cache.php',
		'query-monitor/query-monitor.php',
	);

	/**
	 * BuddyNext itself. The mu-plugin's own safety floor.
	 */
	private const SELF_PLUGINS = array(
		'buddynext/buddynext.php',
		'buddynext-pro/buddynext-pro.php',
	);

	/**
	 * The mu-plugin's keep-alive FLOOR. One definition, rendered into the file.
	 *
	 * Deliberately wider than what sync_option() merges at runtime, and the
	 * difference is not an oversight:
	 *
	 *  - sync_option() merges CORE_INTEGRATIONS + TRANSLATION_PLUGINS + the owner's
	 *    list, and Pro appends its application-layer family through the
	 *    `buddynext_isolation_plugins` filter. That is the correct split - Free
	 *    does not decide Pro's integrations.
	 *  - the mu-plugin cannot wait for any of that. It runs before plugins load,
	 *    so no filter has fired and the option may be empty or stale. Its floor
	 *    therefore hardcodes the whole in-house family, Pro's included, so
	 *    Portfolio tabs and nav survive the very first request.
	 *
	 * What WAS wrong is that this floor existed twice: once here in constants and
	 * once as a hand-written array inside the mu-plugin source in Installer, held
	 * together by a comment reading "keep in sync". A comment is not a sync
	 * mechanism. Installer now renders this list into the generated file, so the
	 * copy on disk is derived rather than maintained.
	 *
	 * The generated mu-plugin still contains a literal array, because it must - it
	 * cannot call into this class. Nobody has to type it twice.
	 *
	 * @return array<int,string> Plugin basenames, de-duplicated.
	 */
	public static function essentials(): array {
		return array_values(
			array_unique(
				array_merge(
					self::SELF_PLUGINS,
					self::CORE_INTEGRATIONS,
					self::APP_INTEGRATIONS,
					self::OPERATIONAL_PLUGINS,
					self::TRANSLATION_PLUGINS
				)
			)
		);
	}

	/**
	 * Owner-managed option: extra plugin basenames to keep alive on BN routes.
	 *
	 * Separate from self::OPTION because that one is REWRITTEN from the canonical
	 * family on every sync — an owner's choices stored there would be erased the
	 * next time Pro was toggled. This is the owner's list; sync_option() merges it
	 * into the mirror the mu-plugin reads, so no mu-plugin change is required and
	 * an older on-disk copy keeps working.
	 */
	public const OPTION_KEEP = 'buddynext_isolation_keep';

	/**
	 * String-override plugins that isolation must never strip.
	 *
	 * These do not add a feature — they rewrite EVERY string on the page through
	 * `gettext` / `load_textdomain_mofile`. Stripping one does not disable
	 * something the visitor can see is missing; it silently serves BuddyNext's own
	 * English while the owner's translation sits on disk being ignored, and only on
	 * the hub routes, which is precisely where the terminology matters most
	 * (renaming "Spaces" to "Teams"). A translation plugin is also cheap — Loco's
	 * front-end footprint is a single filter — so this costs nothing measurable
	 * against the memory isolation is there to save.
	 *
	 * Anything not listed here is covered by the owner-facing allow-list screen
	 * (Admin -> BuddyNext -> Plugin isolation), so this is a sensible default, not
	 * the only way in.
	 */
	private const TRANSLATION_PLUGINS = array(
		'loco-translate/loco.php',
		'polylang/polylang.php',
		'polylang-pro/polylang.php',
		'sitepress-multilingual-cms/sitepress.php',
		'wpml-string-translation/plugin.php',
		'translatepress-multilingual/index.php',
		'say-what/say-what.php',
	);

	/**
	 * The owner's extra keep-alive basenames, sanitised.
	 *
	 * @return array<int,string>
	 */
	public static function owner_keep_list(): array {
		$stored = get_option( self::OPTION_KEEP, array() );

		if ( ! is_array( $stored ) ) {
			return array();
		}

		return array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( $p ): string => is_string( $p ) ? trim( $p ) : '',
						$stored
					)
				)
			)
		);
	}

	/**
	 * Wire the runtime option-sync pass.
	 *
	 * @return void
	 */
	public function init(): void {
		// Late on init: Pro's wire_extensions() (plugins_loaded) has already added
		// its `buddynext_isolation_plugins` filter, so the persisted option carries
		// the full free+pro family. The guarded write below is a no-op unless the
		// list actually changed, so this is cheap on every request.
		add_action( 'init', array( $this, 'sync_option' ), 20 );
	}

	/**
	 * The canonical in-house integration allow-list (free + filtered Pro additions).
	 *
	 * @return array<int,string> De-duplicated plugin basenames.
	 */
	public static function integration_plugins(): array {
		/**
		 * Filter the in-house integration plugins kept alive on BuddyNext routes.
		 *
		 * BuddyNext Pro appends its application-layer integrations here. Entries are
		 * plugin basenames (`dir/file.php`); listing one that is not installed is
		 * harmless.
		 *
		 * @param array<int,string> $plugins In-house integration basenames.
		 */
		$base = array_merge(
			self::CORE_INTEGRATIONS,
			self::TRANSLATION_PLUGINS,
			self::owner_keep_list()
		);

		$plugins = (array) apply_filters( 'buddynext_isolation_plugins', $base );

		$plugins = array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( $p ): string => is_string( $p ) ? trim( $p ) : '',
						$plugins
					)
				)
			)
		);

		sort( $plugins ); // Deterministic order so the guarded write only fires on real changes.

		return $plugins;
	}

	/**
	 * Persist the canonical allow-list to the mirror option when it has changed.
	 *
	 * Idempotent: reads the stored JSON, compares against the freshly-collected
	 * list, and only writes on a genuine diff — so it adds no write on a steady
	 * state but self-heals the moment Pro is (de)activated or the family changes.
	 *
	 * @return void
	 */
	public function sync_option(): void {
		$desired = self::integration_plugins();
		$stored  = json_decode( (string) get_option( self::OPTION, '' ), true );

		if ( is_array( $stored ) && $stored === $desired ) {
			return;
		}

		update_option( self::OPTION, (string) wp_json_encode( $desired ), false );
	}
}
